# Generated by Django 4.2.1 on 2023-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0002_remove_review_producrs_review_products_review_stars_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="tags",
            field=models.ManyToManyField(blank=True, to="product.tag"),
        ),
    ]
